FROM phpstorm/php-apache:8.2-xdebug3.2

ENV APACHE_DOCUMENT_ROOT /app/public

COPY web.conf /etc/apache2/sites-available/web.conf

RUN apt-get update \
 && apt-get install -y git supervisor \
 mc \
 cron \
 netcat \
 libicu-dev \
 libxslt-dev \
 libc-client-dev \
 libkrb5-dev \
 && a2ensite web \
 && a2enmod rewrite \
 && curl -sS https://getcomposer.org/installer \
  | php -- --install-dir=/usr/local/bin --filename=composer \
 && echo "AllowEncodedSlashes On" >> /etc/apache2/apache2.conf \
 && rm -rf /var/lib/apt/lists/* \
 && apt-get clean

RUN docker-php-ext-install -j$(nproc) pdo_mysql intl xsl

RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
    && docker-php-ext-install imap

RUN chmod 0777 /var/log

#COPY ./php.ini $PHP_INI_DIR/conf.d/

#ADD ./runner.sh /runner.sh
#RUN chmod a+x /runner.sh
#CMD /runner.sh

WORKDIR /var/www/app
